# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Archivos sesión 4-20211011/Nexys4DDR_Master.xdc

# IP: ip/c_counter_binary_3/c_counter_binary_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_3 || ORIG_REF_NAME==c_counter_binary_3}]

# IP: ip/blk_ram_mem/blk_ram_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_ram_mem || ORIG_REF_NAME==blk_ram_mem}]
